[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
actix-files = "0.6"
image = "0.25"
rstar = "0.11"
parquet = "55"
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
